### PR TITLE
migrate config settings correctly

### LINKED ISSUE #667: ImportError: No module named 'nbextensions'
I got error below this morning:

`[W 09:06:34.744 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "C:\Users\myname\AppData\Local\Programs\Python\Python35\Lib\site-packages\notebook\notebookapp.py", line 1042, in init_server_extensions
        mod = importlib.import_module(modulename)
    File "/opt/python3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
  ImportError: No module named 'nbextensions'`

 and I download the file [IPython-notebook-extensions/extensions/nbextensions.py](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/f7ad9bd853e685ecb096053a5571ecf0e6fbe95a/extensions/nbextensions.py) and save to `C:\Users\myname\AppData\Roaming\jupyter\extensions` 

and then I restart jupyter notebook, no error at all.

seems extensions/nbextensions.py was deleted from the repository at [d076664a20f40b137a2b642d9ea8dd7bdcea2953](https://github.com/ipython-contrib/IPython-notebook-extensions/commit/d076664a20f40b137a2b642d9ea8dd7bdcea2953)

### PR DESCRIPTION
**Pull request by jcb91**
from old `config` name to new `jupyter_nbextensions_configurator`

fixes #667

also addresses the rename issue mentioned in https://github.com/ipython-contrib/IPython-notebook-extensions/issues/653#issuecomment-229820353 (although doesn't fix the bulk of #653)

### CODE REVIEW

**Comment by juhasch** [comment]
I think this PR looks good. 
The one thing I am unsure about is the dependency on  `jupyter_nbextensions_configurator` in `configure_nbextension.py` generally. IMO we should separate extensions and the configurator.

**Comment by jcb91** [comment]
> we should separate extensions and the configurator

yes, I guess we could, it hadn't really occurred to me. In that case we'd need to edit more docs to reflect the change, as a lot of things refer to the config extension provided by this repo. Tbh, this PR is a bit redundant given #671, anyway (since 671 already does this migration).

**Comment by juhasch** [comment]
I think if we move the repository together with #671 to jupyter-contrib, we might leave this repo in a retired state (with links to the new repo). In this case it would make sense to decouple this repo from others, I believe.

**Comment by jcb91** [comment]
> we might leave this repo in a retired state (with links to the new repo)

Yes, that sounds like a reasonable plan.

One slight issue (ha!) is that if we leave this repo here, we'll have to think of some way to sensibly migrate any outstanding issues to the new repo, and get people to add new ones in the correct place, etc. - perhaps asking github to migrate to jupyter-contrib might make that simpler?

**Comment by juhasch** [comment]
Yes, I guess migrating the complete repo is better in the end and will save us some headache.

**Comment by juhasch** [comment]
Closed after restructuring of repo

**Pull request closed without merging**
