### PR TITLE
Fix/reponame

### PR DESCRIPTION
**Pull request by juhasch**
Replace IPython-notebook-extensions with Jupyter-notebook-extensions

### CODE REVIEW

**Comment by jcb91** [comment]
I've started doing omething similar on top of current master. Will PR shortly

**Comment by juhasch** [comment]
OK. Thanks. I have a small patch for setup.py and readme.md coming.

**Comment by jcb91** [comment]
while we're about renaming things, might it be better to rename the repo with the same name as the python package (`jupyter_contrib_nbextensions`)?

**Comment by juhasch** [comment]
Having the same name sounds good.

**Comment by jcb91** [comment]
ok, so I'll go ahead and do that, then do a quick `s/Ipython-notebook-extensions/jupyter_contrib_nbextensions/g`

**Pull request closed without merging**
